### ISSUE TITLE
Empty consent message

### ISSUE THREAD

**Issue by frandelarosa** [quantcast/choice-mobile-ios#1]
Hello,

I'm implementing the choice mobile for iOS and I'm getting this error message:

**ChoiceMobile.ChoiceMobileError.configError(message: "Unexpected config error")**

I've added the pcode in my didFinishLaunchingWithOptions:

`[[ChoiceCmp shared] startChoiceWithPcode:@"<pcode>" delegate:self];`

Also, the message which is shown when the method _[[ChoiceCmp shared] forceDisplayUI]_ is called is empty.

![screen](https://user-images.githubusercontent.com/426402/109004592-3c690c00-76a9-11eb-80e7-be9bb144b444.png)

Any help is welcome!

**Comment by ajith-ab** [comment]
I have facing same issue

**Comment by SmithKevin** [comment]
Hello.  Sorry this wasn't made more clear, but the version posted here is still early beta.   We are actively working on this product and hope to have a GA in the next few weeks.  As such you may still find some bugs or missing features in this 0.0.6 release build.  Please keep an eye on this space for an update in the coming days/weeks.

**Comment by SmithKevin** [comment]
I did want to mention one more thing.  In order for the CMP to work, you must have an account and registered Choice domain on Quantcast.com. https://www.quantcast.com/products/choice-consent-management-platform/
I will be sure to post documentation to this repo when we release the next version

**Comment by SmithKevin** [comment]
This should be fixed now in v0.0.7.
