### ISSUE TITLE
Button title doesn't appear

### ISSUE THREAD

**Issue by frandelarosa** [quantcast/choice-mobile-ios#2]
Hello, I've updated the library to 0.0.7 and the button title doesn't appear.

![Simulator Screen Shot - iPhone 11 Pro - 2021-03-08 at 09 40 03](https://user-images.githubusercontent.com/426402/110296203-592f0900-7ff2-11eb-97c8-bb2934f3beda.png)

Is there any fix to solve it?

Thanks in advance.

**Comment by SmithKevin** [comment]
This should be fixed in the latest version.  Just be sure you have your pcode in the app correct and that your bundleid is registered on quantcast.com
